name: Build for aarch64

on:
  push:

permissions: write-all

jobs:
  help:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
    - uses: actions/checkout@v4

    - name: Create a new tag
      if: 1 == 0
      run: |
        TAG_NAME="nightly"
        git tag $TAG_NAME
        git push origin $TAG_NAME

    - name: HELP
      run: |
        mkdir .zig && cd .zig
        curl -o zig.tar.xz "https://ziglang.org/download/0.13.0/zig-linux-x86_64-0.13.0.tar.xz" && tar -xJf zig.tar.xz && rm zig.tar.xz && mv * 123 && mv 123/* . && rm -d 123 && export PATH=$PWD:$PATH && cd ..
        zig build --help

  Fast:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
    - uses: actions/checkout@v4

    - name: Build
      run: |
        mkdir .zig && cd .zig
        curl -o zig.tar.xz "https://ziglang.org/download/0.13.0/zig-linux-x86_64-0.13.0.tar.xz" && tar -xJf zig.tar.xz && rm zig.tar.xz && mv * 123 && mv 123/* . && rm -d 123 && export PATH=$PWD:$PATH && cd ..
        zig build -Dtarget="aarch64-linux-musl"   --release

    - name: Check
      run: |
        ls -lah zig-out/bin/
        ls -lah zig-out/bin/

  Small:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
    - uses: actions/checkout@v4

    - name: Build
      run: |
        mkdir .zig && cd .zig
        curl -o zig.tar.xz "https://ziglang.org/download/0.13.0/zig-linux-x86_64-0.13.0.tar.xz" && tar -xJf zig.tar.xz && rm zig.tar.xz && mv * 123 && mv 123/* . && rm -d 123 && export PATH=$PWD:$PATH && cd ..
        zig build -Dtarget="aarch64-linux-musl" --release

    - name: Check
      run: |
        ls -la zig-out/bin/
        ls -lah zig-out/bin/




  Default:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
    - uses: actions/checkout@v4

    - name: Build
      run: |
        mkdir .zig && cd .zig
        curl -o zig.tar.xz "https://ziglang.org/download/0.13.0/zig-linux-x86_64-0.13.0.tar.xz" && tar -xJf zig.tar.xz && rm zig.tar.xz && mv * 123 && mv 123/* . && rm -d 123 && export PATH=$PWD:$PATH && cd ..
        zig build

    - name: Check
      run: |
        ls -la zig-out/bin/
        ls -lah zig-out/bin/